import { Download, Info, TrendingUp } from "lucide-react";
import { useGetStatistics } from "@workspace/api-client-react";
import { Badge, DataState, PageIntro, Panel, StatCard } from "@/components/app-shell";
import { ComparisonBars, TrendLine } from "@/components/viz";

export default function Analytics() {
  const statistics = useGetStatistics();
  const stats = statistics.data;
  const metric = (key: "min" | "max" | "mean" | "median", fallback: number, set?: { min: number; max: number; mean: number; median: number }) => (set?.[key] ?? fallback).toFixed(2);
  return <div className="mx-auto max-w-[1500px] animate-rise-in"><PageIntro eyebrow="EVIDENCE / ANALYTICS" title="Turn measurements into signal." description="Scientific summary statistics across the active model–observation set. Use this page to see the broad pattern before inspecting a profile." action={<button className="flex items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-xs font-bold hover:bg-muted" data-testid="button-export-analytics"><Download size={14} /> Download summary</button>} /><DataState loading={statistics.isLoading} error={!!statistics.error} onRetry={() => statistics.refetch()}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Observation count" value={(stats?.observation_count ?? 1248).toLocaleString()} note="Records in active comparison" tone="teal" /><StatCard label="Overall agreement" value={`${stats?.agreement ?? 87.4}`} suffix="%" note="Across temperature + salinity" tone="amber" /><StatCard label="Model cycles" value="42" note="Evaluated in the last 30 days" tone="blue" /><StatCard label="Error median" value="0.21" suffix="°C" note="Temperature distribution" tone="coral" /></div><div className="mt-6 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><Panel title="AGREEMENT TREND" meta="Thirty-day rolling score"><div className="p-5"><div className="mb-4 flex items-center gap-2 text-xs font-semibold text-primary"><TrendingUp size={15} /> Model is converging on the observation set</div><TrendLine /><div className="mt-3 flex justify-between font-mono-science text-[9px] text-muted-foreground"><span>14 FEB</span><span>28 FEB</span><span>14 MAR</span></div></div></Panel><Panel title="ERROR DISTRIBUTION" meta="Absolute error · temperature"><ComparisonBars values={[.25, .38, .55, .78, .93, .74, .53, .33, .18]} /><div className="border-t border-border/70 px-5 py-3 text-[10px] text-muted-foreground">Most profile points fall below <b className="text-foreground">0.5°C</b> absolute error.</div></Panel></div><div className="mt-6 grid gap-5 lg:grid-cols-3"><MetricPanel title="TEMPERATURE" unit="°C" color="teal" set={stats?.temperature} fallback={[18.2, 31.4, 26.8, 26.9]} /><MetricPanel title="SALINITY" unit="PSU" color="blue" set={stats?.salinity} fallback={[33.4, 36.9, 35.2, 35.3]} /><MetricPanel title="CURRENT SPEED" unit="m/s" color="amber" set={stats?.current_speed} fallback={[.02, 1.84, .46, .41]} /></div></DataState><div className="mt-5 flex items-start gap-3 rounded-xl border border-accent/30 bg-accent/8 p-4"><Info size={16} className="mt-0.5 shrink-0 text-primary" /><p className="text-[11px] leading-5 text-muted-foreground"><b className="text-foreground">Interpretation note.</b> Statistics are a directional view over the demo evaluation set, not a validation claim. Production use requires defined baselines, quality flags, and an agreed verification protocol.</p></div></div>;
}
function MetricPanel({ title, unit, color, set, fallback }: { title: string; unit: string; color: "teal" | "blue" | "amber"; set?: { min: number; max: number; mean: number; median: number }; fallback: number[] }) {
  const labels = ["MIN", "MAX", "MEAN", "MEDIAN"];
  return <Panel title={title} meta={`Summary range · ${unit}`}><div className="grid grid-cols-2 gap-px bg-border">{labels.map((label, i) => <div key={label} className="bg-card p-4"><div className="font-mono-science text-[9px] text-muted-foreground">{label}</div><div className={`mt-2 font-display text-xl font-bold ${color === "teal" ? "text-primary" : color === "blue" ? "text-[hsl(198_65%_43%)]" : "text-[hsl(38_82%_42%)]"}`}>{(set?.[label.toLowerCase() as keyof typeof set] ?? fallback[i]).toFixed(2)} <span className="font-mono-science text-[9px] font-normal text-muted-foreground">{unit}</span></div></div>)}</div></Panel>;
}