import { Link } from "wouter";
import { ArrowRight, Database, Eye, Layers3, MapPinned, Minus, Plus, RefreshCw, Waves } from "lucide-react";
import { useHealthCheck, useListDatasets, useListObservations, useGetStatistics, useGetOceanSlice } from "@workspace/api-client-react";
import { Badge, DataState, PageIntro, Panel, StatCard } from "@/components/app-shell";
import { ComparisonBars, FieldCanvas, MiniMap, TrendLine } from "@/components/viz";

export default function Dashboard() {
  const health = useHealthCheck();
  const datasets = useListDatasets();
  const observations = useListObservations();
  const stats = useGetStatistics();
  const slice = useGetOceanSlice({ variable: "temperature", depth: 0, time: "2026-01-05" });
  const datasetCount = datasets.data?.length ?? 4;
  const obsCount = stats.data?.observation_count ?? observations.data?.length ?? 1248;
  return <div className="mx-auto max-w-[1500px] animate-rise-in">
    <PageIntro eyebrow="MISSION DESK / 26.067" title="Read the ocean as a system." description="A focused workspace for Indian Ocean model fields, in-water observations, and the gap between them." action={<div className="flex items-center gap-2"><Badge tone="amber">DEMO DATA</Badge><Badge tone={health.data ? "teal" : "neutral"}>{health.data ? "API ONLINE" : "SYNCING"}</Badge></div>} />
    <div className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <StatCard label="Observed platforms" value={obsCount.toLocaleString()} note="Argo, glider, CTD + BGC" tone="teal" />
      <StatCard label="Model agreement" value={`${stats.data?.agreement ?? 87.4}`} suffix="%" note="Across active comparison set" tone="amber" />
      <StatCard label="Active datasets" value={String(datasetCount).padStart(2, "0")} note="4 model + observation layers" tone="blue" />
      <StatCard label="Last model cycle" value="06:00" suffix="UTC" note="HYCOM-IO / 14 Mar 2024" tone="coral" />
    </div>
    <div className="mb-6 grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(320px,.6fr)]">
      <Panel className="overflow-hidden" title="FIELD SNAPSHOT" meta="Surface temperature · 05 JAN 2026 · 0 M" action={<Link href="/explorer" className="mr-5 flex items-center gap-1 text-[11px] font-bold text-primary hover:gap-2" data-testid="link-open-field">Open field <ArrowRight size={14} /></Link>}><div className="p-4 sm:p-5"><DataState loading={slice.isLoading} error={!!slice.error} onRetry={() => slice.refetch()}><FieldCanvas slice={slice.data} /></DataState></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-border/70 px-5 py-3"><div className="flex gap-4 font-mono-science text-[10px] text-muted-foreground"><span>MIN <b className="text-foreground">{slice.data?.min?.toFixed(2) ?? "—"}°C</b></span><span>MEAN <b className="text-foreground">{slice.data?.mean?.toFixed(2) ?? "—"}°C</b></span><span>MAX <b className="text-foreground">{slice.data?.max?.toFixed(2) ?? "—"}°C</b></span></div><span className="text-[10px] text-muted-foreground">Downsampled preview · 16 × 20 grid</span></div></Panel>
      <Panel className="overflow-hidden" title="SITUATIONAL AWARENESS" meta="Current observation footprint"><div className="p-4"><MiniMap /><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-lg bg-muted/60 p-3"><div className="font-mono-science text-[9px] uppercase text-muted-foreground">Argo</div><div className="mt-1 font-display text-xl font-bold">1,104</div></div><div className="rounded-lg bg-muted/60 p-3"><div className="font-mono-science text-[9px] uppercase text-muted-foreground">Gliders</div><div className="mt-1 font-display text-xl font-bold">08</div></div></div></div></Panel>
    </div>
    <div className="mb-6 grid gap-5 lg:grid-cols-[.92fr_1.08fr]">
      <Panel title="THE WORKFLOW" meta="From model field to defensible signal"><div className="divide-y divide-border/70"><Link href="/explorer" className="group flex items-center gap-4 p-5 hover:bg-muted/45" data-testid="link-workflow-explore"><div className="grid size-10 place-items-center rounded-lg bg-primary text-primary-foreground"><Layers3 size={18} /></div><div className="flex-1"><div className="font-display text-base font-bold">01 / Explore</div><p className="mt-1 text-xs text-muted-foreground">Move through depth, time, and variable without losing the geographic frame.</p></div><ArrowRight size={16} className="text-muted-foreground transition-transform group-hover:translate-x-1" /></Link><Link href="/observations" className="group flex items-center gap-4 p-5 hover:bg-muted/45" data-testid="link-workflow-observe"><div className="grid size-10 place-items-center rounded-lg border border-accent bg-accent/15 text-primary"><Eye size={18} /></div><div className="flex-1"><div className="font-display text-base font-bold">02 / Observe</div><p className="mt-1 text-xs text-muted-foreground">Locate the platforms that anchor the model to the living ocean.</p></div><ArrowRight size={16} className="text-muted-foreground transition-transform group-hover:translate-x-1" /></Link><Link href="/comparison" className="group flex items-center gap-4 p-5 hover:bg-muted/45" data-testid="link-workflow-compare"><div className="grid size-10 place-items-center rounded-lg bg-[hsl(38_82%_58%)] text-[hsl(201_48%_16%)]"><RefreshCw size={18} /></div><div className="flex-1"><div className="font-display text-base font-bold">03 / Compare</div><p className="mt-1 text-xs text-muted-foreground">See where a model diverges, and whether the divergence matters.</p></div><ArrowRight size={16} className="text-muted-foreground transition-transform group-hover:translate-x-1" /></Link></div></Panel>
      <Panel title="SIGNAL OVERVIEW" meta="Rolling model–observation agreement · 30 days"><div className="p-5"><div className="mb-4 flex items-end justify-between"><div><div className="font-display text-3xl font-bold">87.4<span className="text-lg text-muted-foreground">%</span></div><div className="mt-1 flex items-center gap-1 text-[11px] font-semibold text-primary">+3.8% <span className="font-normal text-muted-foreground">from previous cycle</span></div></div><div className="flex gap-1.5"><button className="rounded-md border border-border p-1.5 text-muted-foreground hover:bg-muted" data-testid="button-chart-minus"><Minus size={13} /></button><button className="rounded-md border border-border p-1.5 text-muted-foreground hover:bg-muted" data-testid="button-chart-plus"><Plus size={13} /></button></div></div><TrendLine /><div className="mt-3 flex justify-between font-mono-science text-[9px] text-muted-foreground"><span>14 FEB</span><span>01 MAR</span><span>14 MAR</span></div></div></Panel>
    </div>
    <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
      <Panel title="ACTIVE DATA LAYERS" meta="Available in the current session"><DataState loading={datasets.isLoading} error={!!datasets.error} empty={!datasets.isLoading && !datasets.data?.length} onRetry={() => datasets.refetch()}><div className="divide-y divide-border/70">{(datasets.data ?? []).slice(0, 4).map((dataset) => <div key={dataset.id} className="flex items-center gap-3 px-5 py-3.5"><div className="grid size-8 place-items-center rounded-md bg-muted text-primary"><Database size={15} /></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold">{dataset.name}</div><div className="mt-1 font-mono-science text-[9px] text-muted-foreground">{dataset.type} · {dataset.source}</div></div><Badge tone={dataset.status === "ready" ? "teal" : "amber"}>{dataset.status}</Badge></div>)}</div></DataState></Panel>
      <Panel title="DECISION CONTEXT" meta="Why this workspace exists"><div className="p-5"><div className="mb-4 flex size-10 items-center justify-center rounded-lg bg-[hsl(38_82%_58%_/_0.18)] text-[hsl(38_82%_38%)]"><MapPinned size={19} /></div><p className="text-sm leading-6 text-foreground/80">A model field becomes useful when a human can place it beside evidence. IBVAP is shaped for rapid ocean intelligence in disaster management and operational planning.</p><Link href="/about" className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-primary hover:gap-3" data-testid="link-read-context">Read the scope note <ArrowRight size={14} /></Link></div></Panel>
    </div>
  </div>;
}